                                <table cellspacing="0" class="shop_table cart">
                                    <thead>
                                        <tr>
                                            <th class="product-remove">codice</th>
                                            <th class="product-name">prodotto</th>
                                            <th class="product-price">prezzo</th>
                                            <th class="product-quantity">quantità</th>
                                            <th class="product-subtotal">totale</th>
                                        </tr>
                                    </thead>
                                    <tbody>
	<FORM ACTION="carrelloaggiungi.asp?Tipo=Aggiungi" METHOD="post">
	<TR>
		<TD><FONT FACE="Verdana" SIZE="1"><INPUT TYPE="text" NAME="Codice" SIZE="10"></FONT></TD>
		<TD><FONT FACE="Verdana" SIZE="1"><TEXTAREA rows=5 cols=20  NAME="Descrizione"></TEXTAREA></FONT></TD>
		<TD><FONT FACE="Verdana" SIZE="1"><INPUT TYPE="text" NAME="Quantita" SIZE="5" VALUE="0"></FONT></TD>
		<TD><FONT FACE="Verdana" SIZE="1"><INPUT TYPE="text" NAME="Prezzou" SIZE="9" VALUE="0"></FONT></TD>
		<TD class="tx1"><input type="submit" value="agg. articolo" name="aggiorna" class="button"></TD>
	</TR>
	</FORM>
</TABLE>
<br>
