<table style=" border:1px solid #d1d0d0;" cellPadding="0" cellSpacing="0" width="400" class="tx12 nero"> 
	<tr><td colspan=2 align=center ><STRONG>>>> I TUOI DATI AZIENDALI (SEGUE FATTURA)</STRONG></td></tr>	
	<tr><td colspan="2" bgcolor="#d1d0d0" height="1px"></td></tr>
	<tr>
		<td align=left >&nbsp;Nome Azienda (ragione sociale):<br>&nbsp;Omettere se privato<font color="DARKORANGE">*</font></td>
		<td align=left >&nbsp;<STRONG><%=ucase(text_Azienda)%></STRONG></td>
	</tr>
	<tr><td colspan="2" bgcolor="#d1d0d0" height="1px"></td></tr>
	<tr>
		<td align=left >&nbsp;Cognome/Referente:<font color="DARKORANGE">*</font></td>
		<td align=left >&nbsp;<STRONG><%=ucase(text_Cognome)%></STRONG></td>
	</tr>				               
	<tr><td colspan="2" bgcolor="#d1d0d0" height="1px"></td></tr>				
	<tr>
		<td align=left >&nbsp;Nome:<font color="DARKORANGE">*</font></td>
		<td align=left >&nbsp;<STRONG><%=ucase(text_Nome)%></STRONG></td>
	</tr>
	<tr><td colspan="2" bgcolor="#d1d0d0" height="1px"></td></tr>							               
	<tr>
		<td align=left >&nbsp;Partita Iva :<br>&nbsp;Omettere se privato<font color="DARKORANGE">*</font></td>
		<td align=left >&nbsp;<STRONG><%=ucase(text_Partitaiva)%></STRONG></td>
	</tr>	
	<tr><td colspan="2" bgcolor="#d1d0d0" height="1px"></td></tr>				
	<tr>
		<td align=left >&nbsp;Indirizzo/Sede dell'azienda:<br>&nbsp;<em><b>Proprio indirizzo se privato</b></em><font color="DARKORANGE">*</font></td>
		<td align=left >&nbsp;<STRONG><%=ucase(text_Indirizzo)%></STRONG></td>
	</tr>
	<tr><td colspan="2" bgcolor="#d1d0d0" height="1px"></td></tr>										
	<tr>
		<td align=left >&nbsp;Citta'/Comune:<font color="DARKORANGE">*</font></td>
		<td align=left >&nbsp;<STRONG><%=ucase(text_Citta)%></STRONG></td>
	</tr>
	<tr><td colspan="2" bgcolor="#d1d0d0" height="1px"></td></tr>					
	<tr>
		<td align=left >&nbsp;Cap:<font color="DARKORANGE">*</font></td>
		<td align=left >&nbsp;<STRONG><%=ucase(text_Cap)%></STRONG></td>
	</tr>
	<tr><td colspan="2" bgcolor="#d1d0d0" height="1px"></td></tr>										
	<tr>
		<td align=left >&nbsp;Provincia:<font color="DARKORANGE">*</font></td>
		<td align=left >&nbsp;<STRONG><%=ucase(text_provincia)%></STRONG></td>
	</tr>	
	<tr><td colspan="2" bgcolor="#d1d0d0" height="1px"></td></tr>												
	<tr>
		<td align=left >&nbsp;E-Mail:<font color="DARKORANGE">*</font></td>
		<td align=left >&nbsp;<STRONG><%=ucase(text_Email)%></STRONG></td>
	</tr>
	<tr><td colspan="2" bgcolor="#d1d0d0" height="1px"></td></tr>					
	<tr>
		<td align=left >&nbsp;Telefono/ Cellulare/ Fax:<font color="DARKORANGE">*</font></td>
		<td align=left >&nbsp;<STRONG><%=ucase(text_telefono)%></STRONG></td>
	</tr>
	<tr><td colspan="2" bgcolor="#d1d0d0" height="1px"></td></tr>			
	<tr> 
	  <td colspan="2" align="left"><br>
		In esecuzione D.Lgs. 30.06.2003 n. 196, recante disposizioni a tutela delle persone e degli altri soggetti rispetto al trattamento dei dati personali, dichiaro di aver letto l'apposita <A class="azzurro lnk" href="privacy.asp" target=_new>informativa</A> e fornisco il consenso al trattamento dei miei dati personali. Acconsento a ricevere comunicazioni su novita' e promozioni aziendali.
		Per rimuoversi >>> <a class="azzurro lnk" href='MAILTO:<%=rimozionemail%>'><strong><%=rimozionemail%></strong></a><br></td>
	</tr>
</table>
<br>