<table align=center width="132" border="0" cellspacing="0" cellpadding="0">
                                <br> 
								<tr>
									<td colspan="2" class=menusx>
										&nbsp;News & Sport
									</td>
								</tr>
								<tr>
						            <td><IMG height=8 src="img/spacer.gif" width=8></td>
									<td>
									   
										<font size="1" face="verdana">
										<A class="bianco9" href="../notizie.asp?id=1&amp;Ty=1">News Italia</A><br>
										<A class="bianco9" href="../notizie.asp?id=2&amp;Ty=1">News Mondo</A><br>
										<A class="bianco9" href="../notizie.asp?id=3&amp;Ty=1">Sport</A><br>
										<A class="bianco9" href="../notizie.asp?id=4&amp;Ty=1">Motori</A><br>
										<br>
										</font>
									</td>
								</tr>
								<tr>
									<td colspan="2" class=menusx>
										&nbsp;Films
									</td>
								</tr>
								<tr>
									<td><IMG height=8 src="img/spacer.gif" width=8></td>
									<td>
										<font size="1" face="verdana">
										<A class="bianco9" href="../notizie.asp?id=1&amp;Ty=3">Novità</A><br>
										<br>
										</font> 
									</td>
								</tr>
								<tr>
									<td colspan="2" class=menusx>
										&nbsp;Vip & News
									</td>
								</tr>
								<tr>
									<td><IMG height=8 src="img/spacer.gif" width=8></td>
									<td>
										<font size="1" face="verdana">
										<A class="bianco9" href="../notizie.asp?id=1&amp;Ty=4">Vip</A><br>
										<br>
										</font> 
									</td>
								</tr>
						
								<tr>
									<td class=menusx colspan="2">
										&nbsp;Music
									</td>
								</tr>
								<tr>
									<td><IMG height=8 src="img/spacer.gif" width=8></td>
									<td>
										<font size="1" face="verdana">
										<A class="bianco9" href="../notizie.asp?id=2&amp;Ty=2" >News Personaggi</A><br>
										<br>						
										</font>
									</td>
								</tr>
								<tr>
									<td colspan=2 class=menusx colspan="1">
										Vendo &  Compro &
										Scambio 
									</td>
								</tr>
      							<tr>
									<td>
										<IMG height=8 src="img/spacer.gif" width=8>
									</td>
									<td>
										<font size="1" face="verdana">
										<A class="bianco10" href="../annunci.asp">Annunci</A><br>
										<br>
										</font>
									</td>
								</tr>
								<tr>
									<td class=menusx colspan="2">
									&nbsp;Games & Giochi
									</td>
								</tr>
								<tr>
								<td>
									<IMG height=8 src="img/spacer.gif" width=8>
								</td>
								<td>
									<font size="1" face="verdana">
									<A class="bianco10" href="../giochi.asp">Formula1</A><br>
									<A class="bianco10" href="../giochi.asp">Tetris</A><br>
									<A class="bianco10" href="../giochi.asp">Squali</A><br>
									<A class="bianco10" href="../giochi.asp">Poker</A><br>
									<A class="bianco10" href="../giochi.asp">Altro...</A><br>
									<br>
									</font>
								</td>
							</tr>
								<tr>
									<td class=menusx colspan="2">
										Intrattenimento
									</td>
								</tr>
      							<tr>
									<td>
										<IMG height=8 src="img/spacer.gif" width=8>
									</td>
									<td>
										<font size="1" face="verdana">
										<A class="bianco10" href="chat.asp">Chattiamo...</A><br>
										<A class="bianco10" href="../oroscopo.asp">Oroscopo</A><br>
										<A class="bianco10" href="../massime.asp">Umorismo...</A><br>
										<A class="bianco10" href="../radio.asp">Radio Online</A><br>
										<br>
										</font>
									</td>
								</tr>
								<tr>
									<td class=menusx colspan="2">
										Utilita' & Free
									</td>
							    </tr>
							    <tr>
									<td>
										<IMG height=8 src="img/spacer.gif" width=8>
									</td>
									<td>
										<font size="1" face="Verdana">
										<A class="bianco10" href="../codicefiscale.asp">Codice Fiscale</A><br>
										<A class="bianco10" href="../elencotelefonico.asp">Elenco Telefonico</A><br>
										<A class="bianco10" href="../treni.asp">Orario Treni</A><br>
										<A class="bianco10" href="../cap.asp">Cap</A><br>
										<A class="bianco10" href="../bollo.asp">Bollo Auto</A><br>
						                <A class="bianco10" href="http:\\www.costruttori.it\mutuo.asp">Mutuo</A><br>
										<br>
										</font>
									</td>
							    </tr>
								<tr>
									<td class=menusx colspan="2">
										Aiuto in cucina e non....
									</td>
								</tr>
								<tr>
									<td>
										<IMG height=8 src="img/spacer.gif" width=8>
									</td>
									<td>
										<font size="1" face="Verdana">
										<A class="bianco10" href="../cosacucino.asp?grp=Antipasto">Cosa Cucino?</A><br>
										<A class="bianco10" href="../categoria.asp?id=6">Un Regalo...</A><br>
										<br>
										</font>
									</td>
								</td>
								
							</tr>
							<tr>
									<td class=menusx colspan="2">
										Da Parte del Cliente
									</td>
							</tr>
							<tr>
									<td>
										<IMG height=8 src="img/spacer.gif" width=8>
									</td>
									<td>
										<font size="1" face="Verdana">
										<A class="bianco10" href="../carrello.asp">Il Tuo Carrello</A><br>
						                <A class="bianco10" href="../informazioni.asp">Informazioni</A><br>
										<br>
										</font>
									</td>
							</tr>
							<tr>
								<td colspan="2"></td>
							</tr></TBODY>
</table>
