             <div id="page-wrapper">
                <div class="row">
                    <div class="col-lg-12">
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class="col-lg-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                               <li><a href="#"><i class="fa fa-home fa-fw"></i> nome utente :  <%=ucase(session("utentetipo"))%></a></li>
                            </div>
                            
                        </div>
                    </div>
                    <!-- /.col-lg-4 -->
                    <div class="col-lg-4">
                        <div class="panel panel-success">
                            <div class="panel-heading">
                              <li><a href="#"><i class="fa fa-city"></i> provincia : </a><%=Session("provincia_cliente")%></li>
                            </div>
                            
                        </div>
                    </div>
                    <!-- /.col-lg-4 -->
                    <div class="col-lg-4">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <li><a href="#"><i class="fa fa-phone"></i> tel/mobile : </a><%=session("mobile")%></li>
                            </div>
                            
                        </div>
                    </div>
                    <!-- /.col-lg-4 -->
                </div>
                <!-- /.row -->  
				 <!-- /.row -->
                <!-------div class="row">
									             
                    <div class="col-lg-2">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="adindex.asp?scelta=tinteggiatura&dett=imbi"><i class="">INSER. PRATICA</i></a>
                            </div>                            
                        </div>
                    </div>
            
                    <div class="col-lg-2">  
                        <div class="panel panel-default">
                            <div class="panel-heading">
                               <a href="adindex.asp"><i class="">PRATICHE</i></a>
                            </div>
                            
                        </div>
                    </div>
     
                    <div class="col-lg-2">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                              <a href="adindex.asp?scelta=serramenta&dett=infis"><i class="">LEADS CONTATTI</i></a>
                            </div>
							
							 </div>
                    </div>
         
                    <div class="col-lg-2">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                              <a href="adindex.asp?scelta=pavimenti&dett=pavi"><i class="">APPUNTAMENTI</i></a>
                            </div>
                            
                        </div>
                    </div>
      
                    <div class="col-lg-2">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="adindex.asp?scelta=idrauliche&dett=bagn"><i class="">CALENDARIO APP.</i></a>
                            </div>                            
                        </div>
                    </div>
     

                </div------------>
				
