<%
'lettura Parametri da cliente
colorpagina=Session("colorpagina")
titolopagina=Session("titolopagina")
rimozionemail=Session("rimozionemail")
spedizionemail=Session("spedizionemail")
defaultMailfrom=Session("defaultMailfrom")
titolofinepagina=Session("titolofinepagina")
sitourl=Session("sitourl")
colorpopup=Session("colorpopup")
titolobreve=Session("titolobreve")
sitourllogo=Session("sitourllogo")
faxnum=Session("faxnum")
indirizzo=Session("indirizzo")
provincia_cliente=Session("provincia_cliente")

'foto isp'foto isp
sitourlfotocartucce= Session("sitourlfotocartucce")
percorsofotocartucce=Session("percorsofotocartucce")
sitourlfotocartucceg= Session("sitourlfotocartucceg") 
percorsofotocartucceg=Session("percorsofotocartucceg")

'area informatica'area informatica
sitourlfotopc= Session("sitourlfotopc")
percorsofotopc=Session("percorsofotopc")
sitourlfotopcg= Session("sitourlfotopcg")
percorsofotopcg=Session("percorsofotopcg")

'filtro x db esprinet
filtro=Session("filtro")%>