<%

Session("colorpagina")="bgcolor=#ffffff"
Session("titolopagina")="Kiron Partner S.p.A.  tel. +39  fax +39  via ,  "
Session("rimozionemail")="jeniuscommunications@gmail.com"
Session("spedizionemail")="jeniuscommunications@gmail.com"
Session("cartadicredito")="jeniuscommunications@gmail.com"
Session("defaultMailfrom")="jeniuscommunications@gmail.com"
Session("pecmail")=""
Session("stampemail")=""
Session("ragionesocialetesto")="Kiron Partner S.p.A.  "
Session("titolofinepagina")="<br>tel. +39  fax +39  <br> Via , xx  <br>xxx <br>C.F. e P.I. xxxxxxxxx"
Session("sitourl")="https://serenissima.jeniuscommunications.it"
Session("colorpopup")="#C0C0C0"
Session("titolobreve")="Kiron Partner S.p.A.  tel. +39" 
Session("sitourllogo")="https://serenissima.jeniuscommunications.it/images/logomail.jpg"   ' inserire logo con indirizzi e numeri telefonici
'Session("sitourllogo")="img/logo.jpg"  ' inserire logo con indirizzi e numeri telefonici
Session("faxnum")=""
Session("indirizzo")="Via , XX  "
Session("provincia_cliente")=" "
Session("mobile")="39xxxxxx"
Session("facebook")=""
'Session("googlemap")="<iframe src='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2810.373846790591!2d11.671503515549253!3d45.2200047790988!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x477ee211b185f6c5%3A0xeab6dd1022285bc8!2sProgramma%20Ufficio%20S.a.s.!5e0!3m2!1sit!2sit!4v1587912779583!5m2!1sit!2sit' width='600' height='450' frameborder='0' style='border:0;' allowfullscreen='' aria-hidden='false' tabindex='0'></iframe>"
'Session("googlestr")="<iframe src='https://www.google.com/maps/embed?pb=!4v1576572277133!6m8!1m7!1sepvjIbNRg1rHOxNJvmsvrg!2m2!1d41.86777136172065!2d12.59285222233337!3f276.9378!4f0!5f0.7820865974627469' width='600' height='450' frameborder='0' style='border:0;' allowfullscreen=''></iframe>"
Session("partitaiva")=22
Session("partitaivac")=1.22
%>