<table width="753" border="0" cellspacing="0" cellpadding="0" align="center"  bgcolor=<%=color3%>>
	<tr height=23 align=center>
		<td><A class=menubot href="../chisiamo.asp">Chi Siamo</A></td>
		<td><A class=menubot href="../contattaci.asp">Contattaci</A></td>
		<td><A class=menubot href="../pubblicita.asp">Pubblicita</A></td>
		<td><A class=menubot href="../informazioni.asp">Informazioni</A></td>
	</tr>
</table>
<p align="center">
<br><a class="navy11" href="http://www.webhouse.net">2002 WebHouse s.a.s</a>
</p>
