	<table width="100%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td colspan="2">
				<img alt ="" border=0 src="img_merchant/tx_mercati.gif" >
			</td>
		</tr>
		<tr>
            <td><img height=8 src="img_merchant/spacer.gif" width=8></td>
			<td>
				<font size="1" face="verdana">
				<A href="network.asp?id=1">Telecomunicazioni</A><br>
				<A href="network.asp?id=2">Corsi di Formazione</A><br>
				<A href="network.asp?id=3&amp;Ty=1">E-Commerce</A><br>
				<br>
				</font>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<img alt ="" border=0  src="img_merchant/tx_lasocieta.gif"  >
			</td>
		</tr>
		<tr>
			<td><img height=8 src="img_merchant/spacer.gif" width=8></td>
			<td>
				<font size="1" face="verdana">
				<A href="network.asp?id=4">Messaggio Fondatore</A><br>
				<A href="network.asp?id=5">Staff</A><br>
				<A href="network.asp?id=6">Rassegna Stampa</A><br>
				<br>
				</font>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<img alt ="" border=0 src="img_merchant/tx_eventi.gif"  >
			</td>
		</tr>
		<tr>
			<td><img height=8 src="img_merchant/spacer.gif" width=8></td>
			<td>
				<font size="1" face="verdana">
				<A href="network.asp?id=7">Manifestazioni</A><br>
				<br>
				</font> 
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<img alt ="" border=0  src="img_merchant/tx_network.gif"  >
			</td>
		</tr>
		<tr>
			<td><img height=8 src="img_merchant/spacer.gif" width=8></td>
			<td>
				<font size="1" face="verdana">
				<A href="network.asp?id=8">Consulta la Rete</A><br>
				<A href="network.asp?id=9">Norme e Regolamenti</A><br>
				<A href="network.asp?id=10">Piano Marketing</A><br>

				<br>						
				</font>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<img alt ="" src="img_merchant/tx_novita.gif" >
			</td>
		</tr>
		<tr>
		<td>
			<img height=8 src="img_merchant/spacer.gif" width=8>
		</td>
		<td>
			<font size="1" face="verdana">
			<A href="network.asp?id=11">Novita'</A><br>
			
			<br>
			</font>
		</td>
	</tr>
</table>
