<td bgcolor="<%=color3%>">
	<font size="1">
	<IMG height=4 src="img/spacer.gif" width=4><br>
	&nbsp;&nbsp;<A HREF="proc_zoom.asp?<%=proc_spec%>"><img border="0"  src="img/nico_zoom.gif" align=absmiddle>&nbsp;Zoom Pagina</A><br>
	<IMG height=4 src="img/spacer.gif" width=4><br>
	&nbsp;&nbsp;<A HREF="proc_stampa.asp?<%=proc_spec%>"><img border="0" src="img/nico_print.gif" align=absmiddle>&nbsp;Stampa Pagina</A><br>
	<IMG height=4 src="img/spacer.gif" width=4><br>
	&nbsp;&nbsp;<A HREF="proc_stampa.asp?<%=proc_spec%>"><img border="0"  src="img/nico_mail.gif" align=absmiddle>&nbsp;Invia ad un'amico</A><br>
	<IMG height=4 src="img/spacer.gif" width=4><br>
	&nbsp;&nbsp;<A HREF="proc_stampa.asp?id=010"><img border="0"  src="img/nico_forum.gif" align=absmiddle>&nbsp;Partecipa al Forum</A><br>
	<IMG height=4 src="img/spacer.gif" width=4><br>
	&nbsp;&nbsp;<A HREF="index.asp"><img border="0"  src="img/nico_home.gif" align=absmiddle>&nbsp;Home Page</A><br>
	<IMG height=4 src="img/spacer.gif" width=4><br>
	</font>
</td>
