	<%
	'Parametri Merchant
	merchant=118
	%>
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td colspan="2">
				<br><br><br>
			</td>
		</tr>
		<tr>
            <td></td>
			<td>
				<font size="1" face="verdana">
				<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<HR><br>
				<A href="merchant_anagrafica.asp"><img border="0"  src="/admin/imgnew/tasto.gif" align=absmiddle>&nbsp;ANAGRAFICA</A><br>
				<br>
				<hr>
				<br>
				<A href="merchant_articoli.asp?cmd=new&merchant=<%=merchant%>"><img border="0"  src="/admin/imgnew/tasto.gif" align=absmiddle>&nbsp;INSERISCI GLI ARTICOLI</A><br>
				<hr>
				<br>
				<a  href=merchant_adcategorie.asp?><img border=0 src=/admin/imgnew/tasto.gif>&nbsp;GESTIONE CATEGORIE</a><br>
				<hr>
				<a  href=merchant_adsottocategorie.asp?><img border=0 src=/admin/imgnew/tasto.gif>&nbsp;GESTIONE SOTTOCATEGORIE</a><br>
				<hr>
				<a  href=merchant_anagrafica.asp?><img border=0 src=/admin/imgnew/tasto.gif>&nbsp;GESTIONE NEGOZIO</a><br>
				<hr>
				<A  href="../admin/adutentipro.asp"><img border=0 src=/admin/imgnew/exit.gif>&nbsp;Uscita Negozio</a><br>
				<hr>
				<br>
				<br>
				</font>
			</td>
		</tr>
	</table>
