A:hover {text-decoration: underline; color: orange}
A {text-decoration: none;}
BODY
{
    FONT-FAMILY: Verdana;
    FONT-SIZE: 8pt;
    MARGIN-TOP: 1px          
}



.txt_whi {COLOR: #000000; TEXT-DECORATION: none;FONT-FAMILY: Verdana;FONT-SIZE: 9pt;}
.gen {FONT-FAMILY: Verdana;FONT-SIZE: 8pt;COLOR: #000000; TEXT-DECORATION: none;}		

.bianco {FONT-FAMILY: Verdana;FONT-SIZE: 8px;COLOR: #ffffff; TEXT-DECORATION: none;}		
.rosso8 {FONT-FAMILY: Verdana;FONT-SIZE: 8px;COLOR: Red; TEXT-DECORATION: none;}
.rosso10 {FONT-FAMILY: verdana;FONT-SIZE: 10px;COLOR: Navy; TEXT-DECORATION: none;}

.nero {FONT-FAMILY: Verdana;FONT-SIZE: 10px;COLOR: #000000; TEXT-DECORATION: none;}		
.nero:hover{FONT-FAMILY: Verdana;FONT-SIZE: 10px;COLOR: Black; TEXT-DECORATION: UNDERLINE;}		
.nero7 {FONT-FAMILY: Verdana;FONT-SIZE: 9px;COLOR: #000000; TEXT-DECORATION: none;}	
.neronew {FONT-FAMILY: Verdana;FONT-SIZE: 9px;COLOR: #000000; TEXT-DECORATION: none;}	
.neronew:hover {FONT-FAMILY: Verdana;FONT-SIZE: 9px;COLOR: DARKORANGE; TEXT-DECORATION: UNDERLINE;}	
.nero8 {FONT-FAMILY: Verdana;FONT-SIZE: 10px;COLOR: #000000; TEXT-DECORATION: none;}
.nero8:hover {FONT-FAMILY: Verdana;FONT-SIZE: 10px;COLOR: #000000; TEXT-DECORATION: UNDERLINE;}
.nero9 {FONT-FAMILY: Verdana;FONT-SIZE: 11px;COLOR: #000000; TEXT-DECORATION: none;}		
.nero9:hover {FONT-FAMILY: Verdana;FONT-SIZE: 11px;COLOR: Black; TEXT-DECORATION: none;}
.nero10 {FONT-FAMILY: Verdana;FONT-SIZE: 12px;COLOR: #000000; TEXT-DECORATION: none;}	
.nero10:hover {FONT-FAMILY: Verdana;FONT-SIZE: 12px;COLOR: Black; TEXT-DECORATION: UNDERLINE;}		
.nero11{FONT-FAMILY: Verdana;FONT-SIZE: 13px;COLOR: #000000; TEXT-DECORATION: none;}		
.nero11:hover {FONT-FAMILY: Verdana;FONT-SIZE: 13px;COLOR: Navy; TEXT-DECORATION: UNDERLINE;}		

.bianco7 {FONT-FAMILY: Verdana;FONT-SIZE: 9px;COLOR: #ffffff; TEXT-DECORATION: none;}
.bianco8 {FONT-FAMILY: Verdana;FONT-SIZE: 10px;COLOR: #ffffff; TEXT-DECORATION: none;}
.bianco9 {FONT-FAMILY: Verdana;FONT-SIZE: 11px;COLOR: #ffffff; TEXT-DECORATION: none;}
.bianco10 {FONT-FAMILY: Verdana;FONT-SIZE: 12px;COLOR: #ffffff; TEXT-DECORATION: none;}
.bianco11 {FONT-FAMILY: Verdana;FONT-SIZE: 13px;COLOR: #ffffff; TEXT-DECORATION: none;}
.bianco14 {FONT-FAMILY: Verdana;FONT-SIZE: 16px;COLOR: #ffffff; TEXT-DECORATION: none;}

.gray10 {FONT-FAMILY: Verdana;FONT-SIZE: 12px;COLOR: DimGray; TEXT-DECORATION: none;}
.neroarial11{FONT-FAMILY: Arial;FONT-SIZE: 13px;COLOR: #000000; TEXT-DECORATION: UNDERLINE;;}	
.Orange9 {FONT-FAMILY: Verdana;FONT-SIZE: 10px;COLOR: DarkOrange; TEXT-DECORATION: none;font-weight: bold;}
.Orange12 {FONT-FAMILY: Verdana;FONT-SIZE: 12px;COLOR: DarkOrange; TEXT-DECORATION: none;font-weight: bold;}
.Orangenew {FONT-FAMILY: Verdana;FONT-SIZE: 14px;COLOR: DarkOrange; TEXT-DECORATION: none;font-weight: bold;}
.Orange14 {FONT-FAMILY: Arial;FONT-SIZE: 16px;COLOR: DarkOrange; TEXT-DECORATION: none;font-weight: bold;}
.navy11{FONT-FAMILY: Verdana;FONT-SIZE: 13px;COLOR: Navy; TEXT-DECORATION: underline;font-weight: bold;}
.navy10{FONT-FAMILY: Verdana;FONT-SIZE: 12px;COLOR: Navy; TEXT-DECORATION: underline;font-weight: bold;}
.navy10n{FONT-FAMILY: Verdana;FONT-SIZE: 12px;COLOR: Navy; TEXT-DECORATION: none;}
.navy11n{FONT-FAMILY: Verdana;FONT-SIZE: 13px;COLOR: Navy; TEXT-DECORATION: none;}
.navy9{FONT-FAMILY: Verdana;FONT-SIZE: 10px;COLOR: Navy; TEXT-DECORATION: none;}
.navy8n{FONT-FAMILY: Verdana;FONT-SIZE: 9px;COLOR: Navy; TEXT-DECORATION: none;}

.orangesp {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/bottoneara.gif");text-decoration:none;background-color:;COLOR: DarkOrange; font-weight: bold;FONT-SIZE: 12px}
.orangesp:hover {text-decoration:none;background-color:;COLOR: white; font-weight: bold;FONT-SIZE: 12px}

.orange01 {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/bottoneara.gif");text-decoration:none;background-color:;COLOR: DarkOrange; font-weight: bold;FONT-SIZE: 12px}
.orange01:hover {text-decoration:none;background-color:;COLOR: navy; font-weight: bold;FONT-SIZE: 12px}

.menuprod1 {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/bottoneara.gif");text-decoration:none;background-color: #000099;COLOR: Orange; FONT-SIZE: 10pt;width=250px;height=25;font-weight: bold;}
.menuprod1:hover {text-decoration:none;background-color: Darkorange;COLOR: WHITE; FONT-SIZE: 10pt;width=250px;height=25;font-weight: bold;}

.menuprod2 {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/bottoneara.gif");text-decoration:none;background-color: #6666cc;COLOR: White; FONT-SIZE: 10pt;width=250px;height=25;font-weight: bold;}
.menuprod2:hover {text-decoration:none;background-color: Darkorange;COLOR: WHITE; FONT-SIZE: 10pt;width=250px;height=25;font-weight: bold;}

.menuprod3 {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/bottone.gif");text-decoration:none;background-color: GRAY;COLOR: White; FONT-SIZE: 10pt;width=250px;height=15;}
.menuprod3:hover {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/bottoneg.gif");text-decoration:none;background-color: Darkorange;COLOR: WHITE; FONT-SIZE: 10pt;width=250px;height=15;}

.menuprod4 {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/bottoneg.gif");text-decoration:none;background-color: none;COLOR: Navy; FONT-SIZE: 10pt;width=350px;height=15;}
.menuprod4:hover {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/_next.gif");text-decoration:none;background-color: Darkorange;COLOR: WHITE; FONT-SIZE: 10pt;width=350px;height=15;}

.menuprod5 {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/bottone.gif");text-decoration:none;background-color: none;COLOR: Blue; FONT-SIZE: 10pt;width=350px;height=25;}
.menuprod5:hover {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/bottoneg.gif");text-decoration:none;background-color: Darkorange;COLOR: WHITE; FONT-SIZE: 10pt;width=350px;height=25;}

.menuprod6 {text-decoration:none;background-color: ;COLOR: Darkorange; FONT-SIZE: 7pt;width=260px;height=15;font-weight:bold;}
.menuprod6:hover {text-decoration:none;background-color: Darkorange;COLOR: WHITE; FONT-SIZE: 7pt;width=260px;height=15;}

.menuprod7 {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/bottoner.gif");text-decoration:none;background-color: Gray;COLOR: White; FONT-SIZE: 9pt;width=270px;height=15;}
.menuprod7:hover {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/bottoneg.gif");text-decoration:none;background-color: Darkorange;COLOR: WHITE; FONT-SIZE: 9pt;width=270px;height=15;}

.menuprod8 {text-decoration:none;background-color: Gray;COLOR: Navy; FONT-SIZE: 10pt;width=270px;height=15;}
.menuprod8:hover {text-decoration:none;background-color: Darkorange;COLOR: WHITE; FONT-SIZE: 10pt;width=270px;height=15;}

.menuprod9 {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/bottone.gif");text-decoration:none;background-color: none;COLOR: Navy; FONT-SIZE: 10pt;width=150px;height=11;}
.menuprod9:hover {text-decoration:none;background-color: Darkorange;COLOR: WHITE; FONT-SIZE: 10pt;width=150px;height=11;}

.menuprod10 {text-decoration:none;background-color: none;COLOR: Navy; FONT-SIZE: 10pt;width=150px;height=15;}
.menuprod10:hover {text-decoration:none;background-color: Darkorange;COLOR: WHITE; FONT-SIZE: 10pt;width=150px;height=15;}

.menuprod11 {text-decoration:none;background-color: none;COLOR: Navy; FONT-SIZE: 10pt;width=150px;height=15;}
.menuprod11:hover {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/_next.gif");text-decoration:none;background-color: Darkorange;COLOR: WHITE; FONT-SIZE: 10pt;width=150px;height=15;}

.menuprod12 {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/bottoneG.gif");text-decoration:none;background-color: none;COLOR: White; FONT-SIZE: 8pt;width=220px;height=15;}
.menuprod12:hover {text-decoration:none;background-color: Darkorange;COLOR: WHITE; FONT-SIZE: 8pt;width=220px;height=15;}

.menuprod13 {text-decoration:none;background-color: #000099;COLOR: White; FONT-SIZE: 8pt;width=220px;height=15;}
.menuprod13:hover {text-decoration:none;background-color: Darkorange;COLOR: WHITE; FONT-SIZE: 8pt;width=220px;height=15;}

.menuprod14 {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/cambiocentro2.gif");text-decoration:none;background-color: NONE;}
.menuprod14:hover {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/cambiocentro2.gif");text-decoration:none;background-color: White;width=92px;height=139;}

.menuprod15 {text-decoration:none;background-color: ;COLOR: Navy; FONT-SIZE: 9pt;}


.menutop {text-decoration:none;background-color: #b4b4fe;COLOR: Navy; FONT-SIZE: 9pt;font-weight:bold;}
.menutop:hover {text-decoration:none; background-color: none;COLOR: white; ;FONT-SIZE: 9pt;font-weight:bold;}

.menutop1 {text-decoration:none;background-color: #000099;COLOR: Darkorange; FONT-SIZE: 9pt;font-weight:bold;}
.menutop1:hover {text-decoration:none; background-color: none;COLOR: white; ;FONT-SIZE: 9pt;font-weight:bold;}

.menutop2 {text-decoration:none;background-color: ff5f00;COLOR:navy; FONT-SIZE: 9pt;font-weight:bold;}
.menutop2:hover {text-decoration:none; background-color: none;COLOR: white; ;FONT-SIZE: 9pt;font-weight:bold;}


.menusx {text-decoration:none;background-color: #000099;COLOR: DarkOrange; FONT-SIZE: 15px;font-weight:bold;}
.menusx:hover {text-decoration:none; background-color: none;COLOR: White; ;FONT-SIZE: 15px;font-weight:bold;}

.menubot {text-decoration:none;background-color: #6666cc;COLOR: White; FONT-SIZE: 15px;font-weight:bold;}
.menubot:hover {text-decoration:none; background-color: none;COLOR: Orange; ;FONT-SIZE: 15px;font-weight:bold;}

.menubot1 {text-decoration:none;background-color: ff5f00;COLOR:navy; FONT-SIZE: 15px;font-weight:bold;}
.menubot1:hover {text-decoration:none; background-color: none;COLOR: white; ;FONT-SIZE: 15px;font-weight:bold;}


.home3 {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/bottone.gif");text-decoration:none;background-color: none;COLOR: white; FONT-SIZE: 10pt;width=140px;height=15;font-weight:bold;}
.home3:hover {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/_next.gif");text-decoration:none;background-color: White;COLOR: Darkorange; FONT-SIZE: 10pt;width=140px;height=15;font-weight:bold;}

.home4 {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/bottoneg.gif");text-decoration:none;background-color: none;COLOR: Navy; FONT-SIZE: 9pt;width=140px;height=15;font-weight:bold;}
.home4:hover {background-repeat: no-repeat;background-image: url("http://marcocasa/shopitalian/img/_next.gif");text-decoration:none;background-color: White;COLOR: Darkorange; FONT-SIZE: 9pt;width=140px;height=15;font-weight:bold;}

