             <div id="page-wrapper">
                <div class="row">
                    <div class="col-lg-12">
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class="col-lg-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                               <li><a href="#"><i class="fa fa-home fa-fw"></i> nome utente:<%=session("loginnominativo")%> </a></li>
                            </div>
                            
                        </div>
                    </div>
                    <!-- /.col-lg-4 -->
                    <div class="col-lg-4">
                        <div class="panel panel-success">
                            <div class="panel-heading">
                              <li><a href="#"><i class="fa fa-envelope-o"></i> email: </a><%=session("loginmail")%></li>
                            </div>
                            
                        </div>
                    </div>
                    <!-- /.col-lg-4 -->
                    <div class="col-lg-4">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <li><a href="#"><i class="fa fa-phone"></i> tel/mobile: </a><%=session("logintel")%></li>
                            </div>
                            
                        </div>
                    </div>
                    <!-- /.col-lg-4 -->
                </div>
                <!-- /.row -->  
				 <!-- /.row -->
                <div class="row">
									                    <!-- /.col-lg-2 -->
                    <div class="col-lg-2">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="adinsertpratica1.asp"><i class="">INSER. PRATICA</i></a>
                            </div>                            
                        </div>
                    </div>
					
                    <!-- /.col-lg-2 -->
                    <div class="col-lg-2">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                               <a href="adpratiche.asp"><i class="">PRATICHE</i></a>
                            </div>                            
                        </div>
                    </div>
                    <!-- /.col-lg-2 -->
                    <div class="col-lg-2">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                              <a href="adleads.asp"><i class="">LEADS/CONTATTI</i></a>
                            </div>							
							 </div>
                    </div>
                    <!-- /.col-lg-2 -->
                    <div class="col-lg-2">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                              <a href="adappuntamenti.asp"><i class="">APPUNTAMENTI</i></a>
                            </div>
                            
                        </div>
                    </div>
                    <!-- /.col-lg-2 -->
                    <div class="col-lg-2">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="adcalendar.asp"><i class="">CALENDARIO APP.</i></a>
                            </div>                            
                        </div>
                    </div>
                    <!-- /.col-lg-2 -->

                </div>
				
                <!-- /.row --> 